version: '3'
services:
  app:
    build:
      context: ./docker/rails/
    volumes:
      - .:/myapp
      - public_volume:/myapp/public
      - tmp_volume:/myapp/tmp
      - vendor_bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: sh ./docker/rails/entrypoint.sh
  db:
    build:
      context: ./docker/postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
  nginx:
    build:
      context: ./docker/nginx/
    command: /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    volumes:
      - public_volume:/myapp/public
      - tmp_volume:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
  minio:
    image: minio/minio:latest
    ports:
      - 9001:9001
    volumes:
      - minio:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
volumes:
  vendor_bundle:
  public_volume:
  tmp_volume:
  pg_data:
  minio:
    driver: local
